version: '3.6'

networks:
  network:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    hostname: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./mongo-setup.js:/docker-entrypoint-initdb.d/mongo-setup.js
    networks:
      - network